"""Initial complete schema

Revision ID: 02c7ba243688
Revises: 
Create Date: 2026-03-08 15:23:48.844706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c7ba243688'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hmd_contact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_id')
    )
    op.create_table('hmd_newsletter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nl_token_id', sa.String(length=36), nullable=False),
    sa.Column('nl_title', sa.String(length=255), nullable=False),
    sa.Column('nl_subject', sa.String(length=255), nullable=False),
    sa.Column('nl_description', sa.Text(), nullable=False),
    sa.Column('nl_status', sa.String(length=12), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nl_token_id')
    )
    op.create_table('hmd_newsletter_subscribers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ns_token_id', sa.String(length=36), nullable=False),
    sa.Column('ns_email', sa.String(length=255), nullable=False),
    sa.Column('ns_status', sa.String(length=12), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ns_token_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hmd_newsletter_subscribers')
    op.drop_table('hmd_newsletter')
    op.drop_table('hmd_contact')
    # ### end Alembic commands ###
