"""Initial migration

Revision ID: 43a815e0d932
Revises: 
Create Date: 2025-10-30 17:35:21.187742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a815e0d932'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=70), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('job_title', sa.String(length=15), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=15), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=50), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
