"""Initial migration

Revision ID: 53c195183ebf
Revises: 
Create Date: 2026-03-03 17:39:24.422428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c195183ebf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hmd_newsletter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nl_token_id', sa.String(length=36), nullable=False),
    sa.Column('nl_title', sa.String(length=255), nullable=False),
    sa.Column('nl_subject', sa.String(length=255), nullable=False),
    sa.Column('nl_description', sa.Text(), nullable=False),
    sa.Column('nl_status', sa.String(length=12), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nl_token_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hmd_newsletter')
    # ### end Alembic commands ###
