"""Added email field

Revision ID: 6fe417d329c7
Revises: ba5af2a34e34
Create Date: 2026-02-12 19:26:44.902595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fe417d329c7'
down_revision = 'ba5af2a34e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hmd_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=70), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hmd_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
