"""Modify users table structure and modify name from users to hmd_users

Revision ID: ba5af2a34e34
Revises: 2d4505ccccf5
Create Date: 2026-02-12 19:23:33.003757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba5af2a34e34'
down_revision = '2d4505ccccf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hmd_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_token_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=25), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_token_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token_id', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('full_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=70), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('job_title', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('department', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('modified_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('modified_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.drop_table('hmd_users')
    # ### end Alembic commands ###
