"""Update Users data_created adding nullable=False

Revision ID: c7e5dcfd75ea
Revises: c85b6355f1e1
Create Date: 2026-02-14 11:27:24.069631

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7e5dcfd75ea'
down_revision = 'c85b6355f1e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hmd_users', schema=None) as batch_op:
        batch_op.alter_column('date_created',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hmd_users', schema=None) as batch_op:
        batch_op.alter_column('date_created',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
